"""The conversation-title attachment is a serialization boundary for LLM output.

``_ChatSlot.display_title`` is generated by a model
(``chat_title._generate_title_via_kiro``), and the slot's own serialization runs
two scanners over it before the dashboard sees it. ``/api/telemetry/startup`` is
a SECOND boundary for the same field, so it must run them too — the scan is
load-bearing rather than duplicated, because a title set through
``api_chat_slot_resume`` is written to the slot unredacted and nothing upstream
of this handler has sanitised it.

The second invariant here is cache purity: ``cost_breakdown`` returns its
memoised object by reference, so attaching a title in place would write into
module-global state and keep serving that title for the rest of the TTL after the
conversation was renamed or closed.
"""
from types import SimpleNamespace

from kiro_crew.dashboard.handlers.telemetry import _with_conversation_titles
from kiro_crew.dashboard.state import NEW_SESSION_TITLE


def _request(slots: dict) -> SimpleNamespace:
    """Minimal stand-in for the aiohttp request the handler reads."""
    return SimpleNamespace(app={"state": SimpleNamespace(slots=slots)})


def _cost(*slot_keys: str) -> dict:
    return {"conversations": [{"slot": k, "credits": 1.0} for k in slot_keys]}


def test_a_credential_shaped_title_is_redacted():
    # A real AWS-key shape. The scanner recognises it; the point is that this
    # endpoint runs the scanner at all.
    leaked = "notes for AKIA" + "IOSFODNN7EXAMPLE"
    slots = {"chat-1-1": SimpleNamespace(display_title=leaked)}
    out = _with_conversation_titles(_request(slots), _cost("chat-1-1"))
    title = out["conversations"][0]["title"]
    assert "AKIA" + "IOSFODNN7EXAMPLE" not in title
    assert "REDACTED" in title


def test_an_ordinary_title_survives_unchanged():
    slots = {"chat-1-1": SimpleNamespace(display_title="Telemetry cost page")}
    out = _with_conversation_titles(_request(slots), _cost("chat-1-1"))
    assert out["conversations"][0]["title"] == "Telemetry cost page"


def test_the_input_payload_is_not_mutated():
    # cost_breakdown hands back its cache by reference; writing through it would
    # pin this title into module-global state for the rest of the TTL.
    payload = _cost("chat-1-1")
    slots = {"chat-1-1": SimpleNamespace(display_title="Telemetry cost page")}
    out = _with_conversation_titles(_request(slots), payload)
    assert "title" not in payload["conversations"][0]
    assert out["conversations"][0]["title"] == "Telemetry cost page"
    assert out["conversations"][0] is not payload["conversations"][0]


def test_a_closed_conversation_gets_no_title_rather_than_its_key():
    out = _with_conversation_titles(_request({}), _cost("chat-9-9"))
    assert "title" not in out["conversations"][0]


def test_the_placeholder_title_is_treated_as_absent():
    slots = {"chat-1-1": SimpleNamespace(display_title=NEW_SESSION_TITLE)}
    out = _with_conversation_titles(_request(slots), _cost("chat-1-1"))
    assert "title" not in out["conversations"][0]


def test_a_state_without_slots_returns_the_payload_unchanged():
    req = SimpleNamespace(app={"state": SimpleNamespace()})
    payload = _cost("chat-1-1")
    out = _with_conversation_titles(req, payload)
    # Content, not identity: the handler always rebuilds the rows so it can
    # never write into the caller's (cached) object.
    assert out == payload
    assert "title" not in out["conversations"][0]
